In [2]:
import pandas as pd

df = pd.read_csv('olist_sales.csv')
print("Original Data Size: ", df.shape)
df.head() # in ra 5 dong dau

Original Data Size:  (113390, 39)

,Unnamed: 0,order_id,order_item_id,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,product_id,product_category_name,...,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,day_of_purchase,month_of_purchase,year_of_purchase,month/year_of_purchase,order_status,order_unique_id
0,0,00010242fe8c5a6d1ba2dd792cb16214,1,3ce436f183e68e07877b285a838db11a,871766c5855e863f6eccc05f988b23cb,28013,campos dos goytacazes,RJ,4244733e06e7ecb4970a6e2683c13e61,cool_stuff,...,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00,Wednesday,September,2017,September-2017,delivered,00010242fe8c5a6d1ba2dd792cb16214-1
1,1,130898c0987d1801452a8ed92a670612,1,e6eecc5a77de221464d1c4eaff0a9b64,0fb8e3eab2d3e79d92bb3fffbb97f188,75800,jatai,GO,4244733e06e7ecb4970a6e2683c13e61,cool_stuff,...,2017-06-29 02:44:11,2017-07-05 12:00:33,2017-07-13 20:39:29,2017-07-26 00:00:00,Wednesday,June,2017,June-2017,delivered,130898c0987d1801452a8ed92a670612-1
2,2,532ed5e14e24ae1f0d735b91524b98b9,1,4ef55bf80f711b372afebcb7c715344a,3419052c8c6b45daf79c1e426f9e9bcb,30720,belo horizonte,MG,4244733e06e7ecb4970a6e2683c13e61,cool_stuff,...,2018-05-18 12:31:43,2018-05-23 14:05:00,2018-06-04 18:34:26,2018-06-07 00:00:00,Friday,May,2018,May-2018,delivered,532ed5e14e24ae1f0d735b91524b98b9-1
3,3,6f8c31653edb8c83e1a739408b5ff750,1,30407a72ad8b3f4df4d15369126b20c9,e7c828d22c0682c1565252deefbe334d,83070,sao jose dos pinhais,PR,4244733e06e7ecb4970a6e2683c13e61,cool_stuff,...,2017-08-01 18:55:08,2017-08-02 19:07:36,2017-08-09 21:26:33,2017-08-25 00:00:00,Tuesday,August,2017,August-2017,delivered,6f8c31653edb8c83e1a739408b5ff750-1
4,4,7d19f4ef4d04461989632411b7e588b9,1,91a792fef70ecd8cc69d3c7feb3d12da,0bb98ba72dcc08e95f9d8cc434e9a2cc,36400,conselheiro lafaiete,MG,4244733e06e7ecb4970a6e2683c13e61,cool_stuff,...,2017-08-10 22:05:11,2017-08-11 19:43:07,2017-08-24 20:04:21,2017-09-01 00:00:00,Thursday,August,2017,August-2017,delivered,7d19f4ef4d04461989632411b7e588b9-1

In [3]:
df_clean = df.drop_duplicates().fillna(0)
print("After clear data: ", df_clean.shape)

After clear data:  (113390, 39)

In [4]:
print(df_clean.columns.tolist())

['Unnamed: 0', 'order_id', 'order_item_id', 'customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'seller_id', 'seller_city', 'seller_state', 'seller_zip_code_prefix', 'payment_type', 'payment_sequential', 'payment_installments', 'price', 'freight_value', 'payment_value', 'shipping_limit_date', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'day_of_purchase', 'month_of_purchase', 'year_of_purchase', 'month/year_of_purchase', 'order_status', 'order_unique_id']

In [9]:
# Group by theo BANG (customer state)
# Dùng hàm .agg() để thực hiện nhiều phép toán khác nhau trên các cột khác nhau trong cùng lần quét

df_grouped = df_clean.groupby('customer_state').agg({
    'order_id' : 'nunique', # Dùng 'nunique' để đếm số đơn hàng không bị trùng lặp, sum tong so tien thu duoc
    'price' : 'sum' }).reset_index() 

df_grouped = df_grouped.rename(columns={
    'order_id' : 'total_orders',
    'price' : 'total_revenue'
})
df_grouped = df_grouped.sort_values(by="total_revenue", ascending = False)

df_grouped.head(10)

   customer_state  total_orders  total_revenue
25             SP         39951     5236551.68
18             RJ         12169     1822349.10
10             MG         11188     1587955.81
22             RS          5266      755457.68
17             PR          4855      680319.20
23             SC          3492      516809.58
4              BA          3215      513503.50
6              DF          2050      304370.81
8              GO          1911      289315.09
7              ES          1978      275843.00

In [13]:
df_grouped.to_parquet('top_states_revenue.parquet')
print("Save success parquet")

Save success parquet